// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Zb_Hlc9m1XCeh_pBoKiv-zS507KXX2w',
    appId: '1:550735419093:web:6a9a097db329f5fc15345c',
    messagingSenderId: '550735419093',
    projectId: 'fuelme-35a6a',
    authDomain: 'fuelme-35a6a.firebaseapp.com',
    storageBucket: 'fuelme-35a6a.appspot.com',
    measurementId: 'G-NHKM76LCZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9zuVeFJI4WCx-904tuI1X04EzvJo_DI',
    appId: '1:550735419093:android:060542fca643ed4415345c',
    messagingSenderId: '550735419093',
    projectId: 'fuelme-35a6a',
    storageBucket: 'fuelme-35a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhm3aInmPXwX_5cQzYjkCuLCEb7kqxppQ',
    appId: '1:550735419093:ios:94aa06563e7e613215345c',
    messagingSenderId: '550735419093',
    projectId: 'fuelme-35a6a',
    storageBucket: 'fuelme-35a6a.appspot.com',
    iosBundleId: 'com.example.micFuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhm3aInmPXwX_5cQzYjkCuLCEb7kqxppQ',
    appId: '1:550735419093:ios:ae0f9a28205c834215345c',
    messagingSenderId: '550735419093',
    projectId: 'fuelme-35a6a',
    storageBucket: 'fuelme-35a6a.appspot.com',
    iosBundleId: 'com.example.micFuel.RunnerTests',
  );
}
